### ISSUE TITLE
Not working on Mac OS

### ISSUE THREAD

**Issue by dlucanu** [ariesco/CafeInMaude#7]
The command (from README)
```
$ maude src/CafeInMaude.maude
```
does not work because there is no a file src/CafeInMaude.maude. There is instead src/cafeInMaude.maude (with lower-case c), but loading it produces errors and does not load the CafeInMaude tool:
```
$ .../maude-3.1/maude.darwin64 src/cafeInMaude.maude src/cafeInMaude 
		     \||||||||||||||||||/
		   --- Welcome to Maude ---
		     /||||||||||||||||||\
	     Maude 3.1 built: Oct 12 2020 20:13:41
	     Copyright 1997-2020 SRI International
		   Fri Oct  8 19:01:06 2021
Warning: "io.maude", line 377 (mod CIMPA-IO): bad token newProcess.
Warning: "io.maude", line 374 (mod CIMPA-IO): no parse for statement
crl [update-cores-more-required] : < cafeInMaude : CIM | state: updateCores, cores: N, mios: MIOS,
    AtS > => < cafeInMaude : CIM | state: addingCore, cores: N, mios: MIOS, AtS > createInterpreter
    (interpreterManager, cafeInMaude, newProcess) if N > numCoresStarted (MIOS) .
==========================================
erewrite in MTP : run .
rewrites: 73 in 7ms cpu (7ms real) (9573 rewrites/second)
result Configuration: <> < cafeInMaude : CIM | input: empty,state: updateCores,current:_(...),
    output-file: "",tsm: 'TRIV -> 'Elt,hsm: empty,psorts: 'NAT |-> 'Nat,params: '3TUPLE |-> ('C1 ::
    'TRIV,'C2 :: 'TRIV,'C3 :: 'TRIV),msorts:_(...),views: 'Qid,mi: interpreter(0),scoreinfo:_(...),
    ptree:_(...),po: finished,mios: noOccupation,tasks: mtTQueue,cores: 1,indVar: noVar,macros:_(
    ...),proof: "",provenGoals: none,backtrackLevels: 6,file: null,out: "",preparsed: mtRDB >
Warning: "io.maude", line 377 (mod CIMPA-IO): bad token newProcess.
Warning: "io.maude", line 374 (mod CIMPA-IO): no parse for statement
crl [update-cores-more-required] : < cafeInMaude : CIM | state: updateCores, cores: N, mios: MIOS,
    AtS > => < cafeInMaude : CIM | state: addingCore, cores: N, mios: MIOS, AtS > createInterpreter
    (interpreterManager, cafeInMaude, newProcess) if N > numCoresStarted (MIOS) .
==========================================
erewrite in MTP : run .
rewrites: 73 in 4ms cpu (4ms real) (17418 rewrites/second)
result Configuration: <> < cafeInMaude : CIM | input: empty,state: updateCores,current:_(...),
    output-file: "",tsm: 'TRIV -> 'Elt,hsm: empty,psorts: 'NAT |-> 'Nat,params: '3TUPLE |-> ('C1 ::
    'TRIV,'C2 :: 'TRIV,'C3 :: 'TRIV),msorts:_(...),views: 'Qid,mi: interpreter(0),scoreinfo:_(...),
    ptree:_(...),po: finished,mios: noOccupation,tasks: mtTQueue,cores: 1,indVar: noVar,macros:_(
    ...),proof: "",provenGoals: none,backtrackLevels: 6,file: null,out: "",preparsed: mtRDB >
Maude>
```
OS: macOS Big Sur 11.5.1 (20G80)

**Comment by ariesco** [comment]
Dear Doreal,

You are right: it should be cafeInMaude (lower case c). I have updated it. 

I think the problem is your Maude version, it is working in Mac Big Sur in my case, but with the December alpha, which defines the newProcess constant:

Maude alpha132 built: Dec 11 2020 21:39:07

Best regards,
 Adrian

**Comment by dlucanu** [comment]
Thanks for your prompt answer. I downloaded the last alpha version of Maude (alpha136), and the first command from README works, but the second one fails:
```
$ .../Darwin64/maude.darwin64 -allow-files src/cafeInMaude.maude
		     \||||||||||||||||||/
		   --- Welcome to Maude ---
		     /||||||||||||||||||\
	     Maude alpha136 built: Jun  8 2021 16:41:35
	     Copyright 1997-2021 SRI International
		   Fri Oct  8 20:04:32 2021
==========================================
erewrite in MTP : run .
CafeInMaude> load examples/CCIMPG/ABP/abp.cafe .

Error: No such file or directory

CafeInMaude> 
```
The file exists:
```
$ ls examples/CCiMPG/ABP/abp.cafe 
examples/CCiMPG/ABP/abp.cafe
```
Did I miss something?

**Comment by ariesco** [comment]
Sorry I did not mention it, although I updated the readme file when I changed the "C" from the file. The Maude file system "moves" to src, so it should be 

load ../examples/CCIMPG/ABP/abp.cafe .

**Comment by dlucanu** [comment]
Thanks. I figured it out myself as well, using the ls command.

**Comment by dlucanu** [comment]
It would be helpful to update the README file.

**Comment by ariesco** [comment]
You are right, I just did it.

**Comment by dlucanu** [comment]
`CafeInMaude runs in Maude 3.1`???
Is there any file describing how to analyze an example (e.g., ABP) from beginning to end? (the sequence of commands, what (and where) is the output of each command, how to interpret the output).

**Comment by ariesco** [comment]
It only runs with the December alpha (or newer).

ABP is the most complex example and it still requires quite a bit of manual interaction (indicated in the abp2.cafe file).

To keep it simple, 2p-mutex includes a **commands_cimpg.cafe** with the commands to be used (see below).

First, it includes commands to load the files, set the number of cores, and set the output file.

After the eof, there are some commands to start the proof, save it, and load it to check that it worked.

After another eof there is a command to load the file itself, so I usually modify the file and just use the last command to load all of them.

```
load ../examples/CCiMPG/2p-mutex/2p-mutex.cafe .
load ../examples/CCiMPG/2p-mutex/all_proofs.cafe .

set-cores 4 .

set-output ../examples/CCiMPG/2p-mutex/2p-proof.cafe .

eof

:infer-proof inv1 .

:save-proof .

load ../examples/CCiMPG/2p-mutex/2p-proof.cafe .

eof

load ../examples/CCiMPG/2p-mutex/commands_cimpg.cafe .
```

**Comment by dlucanu** [comment]
Thanks. 
By "CafeInMaude runs in Maude 3.1???" I suggested to change in README (sorry for not being explicit).
